version: '3.7'

services:
  sample:
    container_name: gsaldanha/dtjsoftplan-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
