export const sexoOptions = [
  { key: '0', text: 'Selecione o sexo', value: undefined },
  { key: 'm', text: 'MASCULINO', value: 'MASCULINO' },
  { key: 'f', text: 'FEMININO', value: 'FEMININO' },
  { key: 'o', text: 'PREFIRO NÃO INFORMAR', value: 'NAO_INFORMAR' },
];

export const nacionaliadeOptions = [
  { key: 'estado', text: 'Selecione o Estado', value: undefined },
  { key: 'Antiguano', text: 'Antiguano', value: 'Antiguano' },
  { key: 'Argentino', text: 'Argentino', value: 'Argentino' },
  { key: 'Bahamense', text: 'Bahamense', value: 'Bahamense' },
  {
    key: 'Barbadiano, barbadense',
    text: 'Barbadiano, barbadense',
    value: 'Barbadiano, barbadense',
  },
  { key: 'Belizenho', text: 'Belizenho', value: 'Belizenho' },
  { key: 'Boliviano', text: 'Boliviano', value: 'Boliviano' },
  { key: 'Brasileiro', text: 'Brasileiro', value: 'Brasileiro' },
  { key: 'Chileno', text: 'Chileno', value: 'Chileno' },
  { key: 'Colombiano', text: 'Colombiano', value: 'Colombiano' },
  { key: 'Costarriquenho', text: 'Costarriquenho', value: 'Costarriquenho' },
  { key: 'Cubano', text: 'Cubano', value: 'Cubano' },
  { key: 'Dominicano', text: 'Dominicano', value: 'Dominicano' },
  { key: 'Equatoriano', text: 'Equatoriano', value: 'Equatoriano' },
  { key: 'Salvadorenho', text: 'Salvadorenho', value: 'Salvadorenho' },
  { key: 'Granadino', text: 'Granadino', value: 'Granadino' },
  { key: 'Guatemalteco', text: 'Guatemalteco', value: 'Guatemalteco' },
  { key: 'Guianês', text: 'Guianês', value: 'Guianês' },
  { key: 'Guianense', text: 'Guianense', value: 'Guianense' },
  { key: 'Haitiano', text: 'Haitiano', value: 'Haitiano' },
  { key: 'Hondurenho', text: 'Hondurenho', value: 'Hondurenho' },
  { key: 'Jamaicano', text: 'Jamaicano', value: 'Jamaicano' },
  { key: 'Mexicano', text: 'Mexicano', value: 'Mexicano' },
  { key: 'Nicaraguense', text: 'Nicaraguense', value: 'Nicaraguense' },
  { key: 'Panamenho', text: 'Panamenho', value: 'Panamenho' },
  { key: 'Paraguaio', text: 'Paraguaio', value: 'Paraguaio' },
  { key: 'Peruano', text: 'Peruano', value: 'Peruano' },
  { key: 'Portorriquenho', text: 'Portorriquenho', value: 'Portorriquenho' },
  { key: 'Dominicana', text: 'Dominicana', value: 'Dominicana' },
  { key: 'São-cristovense', text: 'São-cristovense', value: 'São-cristovense' },
  { key: 'São-vicentino', text: 'São-vicentino', value: 'São-vicentino' },
  { key: 'Santa-lucense', text: 'Santa-lucense', value: 'Santa-lucense' },
  { key: 'Surinamês', text: 'Surinamês', value: 'Surinamês' },
  { key: 'Trindadense', text: 'Trindadense', value: 'Trindadense' },
  { key: 'Uruguaio', text: 'Uruguaio', value: 'Uruguaio' },
  { key: 'Venezuelano', text: 'Venezuelano', value: 'Venezuelano' },
  { key: 'Alemão', text: 'Alemão', value: 'Alemão' },
  { key: 'Austríaco', text: 'Austríaco', value: 'Austríaco' },
  { key: 'Belga', text: 'Belga', value: 'Belga' },
  { key: 'Croata', text: 'Croata', value: 'Croata' },
  { key: 'Dinamarquês', text: 'Dinamarquês', value: 'Dinamarquês' },
  { key: 'Eslovaco', text: 'Eslovaco', value: 'Eslovaco' },
  { key: 'Esloveno', text: 'Esloveno', value: 'Esloveno' },
  { key: 'Espanhol', text: 'Espanhol', value: 'Espanhol' },
  { key: 'Francês', text: 'Francês', value: 'Francês' },
  { key: 'Grego', text: 'Grego', value: 'Grego' },
  { key: 'Húngaro', text: 'Húngaro', value: 'Húngaro' },
  { key: 'Irlandês', text: 'Irlandês', value: 'Irlandês' },
  { key: 'Italiano', text: 'Italiano', value: 'Italiano' },
  { key: 'Noruego', text: 'Noruego', value: 'Noruego' },
  { key: 'Holandês', text: 'Holandês', value: 'Holandês' },
  { key: 'Polonês', text: 'Polonês', value: 'Polonês' },
  { key: 'Português', text: 'Português', value: 'Português' },
  { key: 'Britânico', text: 'Britânico', value: 'Britânico' },
  { key: 'Inglês', text: 'Inglês', value: 'Inglês' },
  { key: 'Galês', text: 'Galês', value: 'Galês' },
  { key: 'Escocês', text: 'Escocês', value: 'Escocês' },
  { key: 'Romeno', text: 'Romeno', value: 'Romeno' },
  { key: 'Russo', text: 'Russo', value: 'Russo' },
  { key: 'Sérvio', text: 'Sérvio', value: 'Sérvio' },
  { key: 'Sueco', text: 'Sueco', value: 'Sueco' },
  { key: 'Suíço', text: 'Suíço', value: 'Suíço' },
  { key: 'Turco', text: 'Turco', value: 'Turco' },
  { key: 'Ucraniano', text: 'Ucraniano', value: 'Ucraniano' },
  { key: 'Americano', text: 'Americano', value: 'Americano' },
  { key: 'Canadense', text: 'Canadense', value: 'Canadense' },
  { key: 'Angolano', text: 'Angolano', value: 'Angolano' },
  { key: 'Moçambicano', text: 'Moçambicano', value: 'Moçambicano' },
  { key: 'Sul-africano', text: 'Sul-africano', value: 'Sul-africano' },
  { key: 'Zimbabuense', text: 'Zimbabuense', value: 'Zimbabuense' },
  { key: 'Argélia', text: 'Argélia', value: 'Argélia' },
  { key: 'Comorense', text: 'Comorense', value: 'Comorense' },
  { key: 'Egípcio', text: 'Egípcio', value: 'Egípcio' },
  { key: 'Líbio', text: 'Líbio', value: 'Líbio' },
  { key: 'Marroquino', text: 'Marroquino', value: 'Marroquino' },
  { key: 'Ganés', text: 'Ganés', value: 'Ganés' },
  { key: 'Queniano', text: 'Queniano', value: 'Queniano' },
  { key: 'Ruandês', text: 'Ruandês', value: 'Ruandês' },
  { key: 'Ugandense', text: 'Ugandense', value: 'Ugandense' },
  { key: 'Bechuano', text: 'Bechuano', value: 'Bechuano' },
  { key: 'Marfinense', text: 'Marfinense', value: 'Marfinense' },
  { key: 'Camaronense', text: 'Camaronense', value: 'Camaronense' },
  { key: 'Nigeriano', text: 'Nigeriano', value: 'Nigeriano' },
  { key: 'Somali', text: 'Somali', value: 'Somali' },
  { key: 'Australiano', text: 'Australiano', value: 'Australiano' },
  { key: 'Neozelandês', text: 'Neozelandês', value: 'Neozelandês' },
  { key: 'Afegão', text: 'Afegão', value: 'Afegão' },
  { key: 'Saudita', text: 'Saudita', value: 'Saudita' },
  { key: 'Armeno', text: 'Armeno', value: 'Armeno' },
  { key: 'Bangladesh', text: 'Bangladesh', value: 'Bangladesh' },
  { key: 'Chinês', text: 'Chinês', value: 'Chinês' },
  {
    key: 'Norte-coreano, coreano',
    text: 'Norte-coreano, coreano',
    value: 'Norte-coreano, coreano',
  },
  { key: 'Sul-coreano, coreano', text: 'Sul-coreano, coreano', value: 'Sul-coreano, coreano' },
  { key: 'Indiano', text: 'Indiano', value: 'Indiano' },
  { key: 'Indonésio', text: 'Indonésio', value: 'Indonésio' },
  { key: 'Iraquiano', text: 'Iraquiano', value: 'Iraquiano' },
  { key: 'Iraniano', text: 'Iraniano', value: 'Iraniano' },
  { key: 'Israelita', text: 'Israelita', value: 'Israelita' },
  { key: 'Japonês', text: 'Japonês', value: 'Japonês' },
  { key: 'Malaio', text: 'Malaio', value: 'Malaio' },
  { key: 'Nepalês', text: 'Nepalês', value: 'Nepalês' },
  { key: 'Omanense', text: 'Omanense', value: 'Omanense' },
  { key: 'Paquistanês', text: 'Paquistanês', value: 'Paquistanês' },
  { key: 'Palestino', text: 'Palestino', value: 'Palestino' },
  { key: 'Qatarense', text: 'Qatarense', value: 'Qatarense' },
  { key: 'Sírio', text: 'Sírio', value: 'Sírio' },
  { key: 'Cingalês', text: 'Cingalês', value: 'Cingalês' },
  { key: 'Tailandês', text: 'Tailandês', value: 'Tailandês' },
  { key: 'Timorense, maubere', text: 'Timorense, maubere', value: 'Timorense, maubere' },
  { key: 'Árabe, emiratense', text: 'Árabe, emiratense', value: 'Árabe, emiratense' },
  { key: 'Vietnamita', text: 'Vietnamita', value: 'Vietnamita' },
  { key: 'Iemenita', text: 'Iemenita', value: 'Iemenita' },
];
